namespace BlokeBot.Site.Content;

internal static class SiteRoutes
{
    internal static IReadOnlyList<string> All { get; } =
    [
        "/",
        "/how-it-works",
        "/install",
        "/privacy",
        "/guide",
        "/guide/getting-started",
        "/dashboard",
        "/channels",
        "/connect",
        "/tools",
        "/plugins",
        "/configuration-transfer",
        "/overlays",
        "/overlays/cues",
        "/overlays/media",
        "/community/request-boards",
        "/community/play-with-viewers",
        "/community/moments",
        "/community/passports",
        "/community/bounties",
        "/community/progression",
        "/community/competitions",
        "/community/raid-collaboration",
        "/community/blokeraid",
        "/community/collectives",
        "/community/bingo",
        "/twitch-operations",
        "/twitch-operations/polls",
        "/twitch-operations/clips-markers",
        "/twitch-operations/channel-points",
        "/twitch-operations/predictions",
        "/commands",
        "/commands/catalog",
        "/guessing",
        "/points",
        "/giveaways",
        "/leaderboards",
        "/automations",
        "/automations/events",
        "/automations/actions",
        "/plugin-development",
        "/plugin-development/manifest",
        "/plugin-development/lua-sdk",
        "/plugin-development/handlers",
        "/plugin-development/host-api",
        "/plugin-development/pages",
        "/plugin-development/automations",
        "/plugin-development/test-publish",
        "/plugin-development/troubleshooting",
        "/troubleshooting",
        "/moderators",
        "/server-owners/plugins",
        "/server-owners",
    ];

    internal static IReadOnlyList<string> GuideTopics { get; } = All.Skip(5).ToArray();
}
