---@meta

-- Generated from BlokeBot host API v1 for Lua 5.4.
-- Regenerate with blokebot-plugin generate; do not edit this file.

---@alias BlokeBotValue nil|boolean|number|string|BlokeBotValue[]|table<string, BlokeBotValue>
---@alias BlokeBotDiagnosticLevel "trace"|"information"|"warning"|"error"
---@alias BlokeBotOverlayTargetId string
---@alias BlokeBotOverlayCueId string
---@alias BlokeBotPointAmount string
---@alias BlokeBotPointBalance string
---@alias BlokeBotScheduleId string
---@alias BlokeBotScheduleInput table<string, BlokeBotValue>
---@alias BlokeBotSqlParameter nil|boolean|number|string
---@alias BlokeBotSqlParameters table<string, BlokeBotSqlParameter>
---@alias BlokeBotSqlRow table<string, BlokeBotSqlParameter>
---@alias BlokeBotProtectedValue string

---@class BlokeBotCommandInput
---@field route string
---@field arguments string[]
---@class BlokeBotWebInput: table<string, BlokeBotValue>
---@class BlokeBotPageInput: table<string, BlokeBotValue>

---@class BlokeBotInstallationSettings: table<string, BlokeBotValue>
---@class BlokeBotFeatureSettings: table<string, BlokeBotValue>

---@alias BlokeBotHostFailureCode "invalidArguments"|"contextNotPermitted"|"notFound"|"conflict"|"unavailable"|"providerRejected"
---@alias BlokeBotCancellationReason "callerRequested"|"pluginDisabled"|"pluginUpdating"|"workerStopping"|"deadlineExceeded"
---@class BlokeBotHostFailure
---@field kind "failed"
---@field code BlokeBotHostFailureCode
---@field safeMessage string
---@class BlokeBotHostCancellation
---@field kind "cancelled"
---@field reason BlokeBotCancellationReason
---@alias BlokeBotHostTerminalOutcome BlokeBotHostFailure|BlokeBotHostCancellation

---@class BlokeBotActorContext
---@field login string
---@field displayName string
---@field twitchUserId? string
---@field isBroadcaster boolean
---@field isModerator boolean
---@field isSubscriber boolean
---@class BlokeBotStreamContext
---@field streamId? string
---@field isLive boolean
---@class BlokeBotCommandContext
---@field route string
---@field arguments string[]
---@class BlokeBotEventContext
---@field handlerId string
---@field source string
---@field eventId string
---@field occurredAt string
---@class BlokeBotScheduleContext
---@field handlerId string
---@field scheduleId string
---@field dueAt string
---@class BlokeBotWebContext
---@field kind "webhook"|"action"
---@field routeId string
---@field method string
---@class BlokeBotAutomationContext
---@field definitionId string
---@field invocationId string
---@class BlokeBotMigrationContext
---@field migrationId string
---@field fromVersion string
---@field toVersion string
---@class BlokeBotPageContext
---@field pageId string
---@field sessionId string

---@class BlokeBotContextBase
---@field pluginId string
---@field pluginVersion string
---@field pluginTag string
---@class BlokeBotInstallationContext: BlokeBotContextBase
---@field kind "installation"
---@class BlokeBotChannelContext: BlokeBotContextBase
---@field kind "channel"
---@field hostId integer
---@field featureId string
---@field actor? BlokeBotActorContext
---@field stream? BlokeBotStreamContext
---@field command? BlokeBotCommandContext
---@field event? BlokeBotEventContext
---@field schedule? BlokeBotScheduleContext
---@field web? BlokeBotWebContext
---@class BlokeBotAutomationInvocationContext: BlokeBotContextBase
---@field kind "automation"
---@field hostId integer
---@field featureId string
---@field automation BlokeBotAutomationContext
---@class BlokeBotMigrationInvocationContext: BlokeBotContextBase
---@field kind "migration"
---@field migration BlokeBotMigrationContext
---@class BlokeBotPageInvocationContext: BlokeBotContextBase
---@field kind "page"
---@field hostId integer
---@field featureId string
---@field page BlokeBotPageContext
---@alias BlokeBotContext BlokeBotInstallationContext|BlokeBotChannelContext|BlokeBotAutomationInvocationContext|BlokeBotMigrationInvocationContext|BlokeBotPageInvocationContext

---@alias BlokeBotHttpMethod "GET"|"POST"|"PUT"|"PATCH"|"DELETE"|"HEAD"
---@class BlokeBotHttpRequest
---@field method BlokeBotHttpMethod
---@field url string
---@field headers? table<string, string>
---@field body? string
---@class BlokeBotHttpResponse
---@field kind "response"
---@field status integer
---@field headers table<string, string>
---@field bodyBase64 string
---@class BlokeBotHttpRejected
---@field kind "rejected"
---@field code string
---@class BlokeBotHttpFailed
---@field kind "failed"
---@field code string
---@alias BlokeBotHttpOutcome BlokeBotHttpResponse|BlokeBotHttpRejected|BlokeBotHttpFailed

---@class BlokeBotContextModule
local context = {}

---Returns the admitted invocation context. Plugin and feature identities cannot be supplied by the caller.
---@return BlokeBotContext # The exact installation, channel, automation, migration, or page context.
function context.current() end

---@class BlokeBotSettingsModule
local settings = {}

---Returns configured installation settings declared by this plugin.
---@return BlokeBotInstallationSettings # The plugin-specific installation settings.
function settings.installation() end

---Returns configured settings for the admitted host feature.
---@return BlokeBotFeatureSettings # The plugin-specific feature settings.
function settings.feature() end

---@class BlokeBotDiagnosticsModule
local diagnostics = {}

---Writes a redaction-safe plugin diagnostic.
---@param level BlokeBotDiagnosticLevel # The diagnostic severity.
---@param message string # The safe diagnostic text.
---@return nil # No value.
function diagnostics.log(level, message) end

---@class BlokeBotResponsesModule
local responses = {}

---Replies in the admitted channel.
---@param message string # The response text.
---@return nil # No value.
function responses.chat(message) end

---Replies privately to the admitted actor.
---@param message string # The response text.
---@return nil # No value.
function responses.whisper(message) end

---@class BlokeBotChatModule
local chat = {}

---Sends a message to the admitted channel.
---@param message string # The chat message text.
---@return nil # No value.
function chat.send(message) end

---@class BlokeBotOverlayModule
local overlay = {}

---Admits an overlay cue for the current channel.
---@param target_id BlokeBotOverlayTargetId # The overlay target UUID.
---@param cue_id BlokeBotOverlayCueId # The overlay cue UUID.
---@return nil # No value.
function overlay.play_cue(target_id, cue_id) end

---@class BlokeBotPointsModule
local points = {}

---Adds a non-negative point amount to a viewer balance.
---@param viewer string # The viewer login.
---@param amount BlokeBotPointAmount # The invariant non-negative amount.
---@param reason string # The audit reason.
---@return BlokeBotPointBalance # The resulting invariant balance.
function points.add(viewer, amount, reason) end

---@class BlokeBotTwitchModule
local twitch = {}

---Creates a Twitch stream marker for the admitted channel.
---@param description string # The marker description.
---@return nil # No value.
function twitch.create_marker(description) end

---@class BlokeBotSchedulesModule
local schedules = {}

---Creates a one-time feature schedule.
---@param handler_id string # The declared handler ID.
---@param due_at string # The future UTC timestamp in ISO 8601 format.
---@param input BlokeBotScheduleInput # The handler input.
---@return BlokeBotScheduleId # The new schedule UUID.
function schedules.once(handler_id, due_at, input) end

---Creates a recurring feature schedule.
---@param handler_id string # The declared handler ID.
---@param due_at string # The first future UTC timestamp in ISO 8601 format.
---@param interval_seconds integer # The positive whole-second interval.
---@param input BlokeBotScheduleInput # The handler input.
---@return BlokeBotScheduleId # The new schedule UUID.
function schedules.recurring(handler_id, due_at, interval_seconds, input) end

---Cancels a schedule owned by the current feature generation.
---@param schedule_id BlokeBotScheduleId # The schedule UUID.
---@return nil # No value.
function schedules.cancel(schedule_id) end

---@class BlokeBotStorageModule
local storage = {}

---Executes one supported statement against plugin-private SQLite.
---@param sql string # The SQL statement.
---@param parameters BlokeBotSqlParameters # Named scalar parameters without the SQL prefix.
---@return number # The number of changed rows.
function storage.execute(sql, parameters) end

---Queries plugin-private SQLite.
---@param sql string # The SQL query.
---@param parameters BlokeBotSqlParameters # Named scalar parameters without the SQL prefix.
---@return BlokeBotSqlRow[] # The result rows keyed by column name.
function storage.query(sql, parameters) end

---@class BlokeBotHttpModule
local http = {}

---Sends a bounded outbound HTTP request through the host policy.
---@param request BlokeBotHttpRequest # The method, absolute URL, optional headers, and optional UTF-8 body.
---@return BlokeBotHttpOutcome # A tagged response, rejection, or transport failure.
function http.send(request) end

---@class BlokeBot
---@field api_version 1
---@field context BlokeBotContextModule
---@field settings BlokeBotSettingsModule
---@field diagnostics BlokeBotDiagnosticsModule
---@field responses BlokeBotResponsesModule
---@field chat BlokeBotChatModule
---@field overlay BlokeBotOverlayModule
---@field points BlokeBotPointsModule
---@field twitch BlokeBotTwitchModule
---@field schedules BlokeBotSchedulesModule
---@field storage BlokeBotStorageModule
---@field http BlokeBotHttpModule
local blokebot = {
  context = context,
  settings = settings,
  diagnostics = diagnostics,
  responses = responses,
  chat = chat,
  overlay = overlay,
  points = points,
  twitch = twitch,
  schedules = schedules,
  storage = storage,
  http = http,
}
return blokebot
