<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\src\BlokeBot.Core\BlokeBot.Core.csproj" />
    <ProjectReference Include="..\..\src\BlokeBot.Persistence\BlokeBot.Persistence.csproj" />
    <ProjectReference Include="..\..\src\BlokeBot.Simulation\BlokeBot.Simulation.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="TUnit" />
  </ItemGroup>

  <ItemGroup>
    <Content
      Include="..\..\src\BlokeBot.Simulation\appsettings.json"
      Link="appsettings.json"
      CopyToOutputDirectory="PreserveNewest"
    />
  </ItemGroup>
</Project>
