namespace BlokeBot.Plugins.Contracts;

public static class PluginContractLimits
{
    public const int MaximumManifestBytes = 256 * 1024;
    public const int MaximumPackageEntries = 512;
    public const long MaximumPackageBytes = 64L * 1024 * 1024;
    public const int MaximumLuaModuleBytes = 1024 * 1024;
    public const int MaximumBrowserAssetBytes = 4 * 1024 * 1024;
    public const int MaximumMediaAssetBytes = 32 * 1024 * 1024;
    public const long MaximumDeclaredPayloadBytes = MaximumPackageBytes;
    public const int MaximumDeclarationsPerSurface = 128;
    public const int MaximumNameCharacters = 120;
    public const int MaximumDescriptionCharacters = 1_000;
    public const int MaximumPluginValueDepth = 16;
    public const int MaximumPluginValueNodes = 1_024;
    public const int MaximumPluginValueStringBytes = 64 * 1024;
    public const int MaximumPluginValuePayloadBytes = 256 * 1024;
    public const int MaximumHostFailureSafeMessageCharacters = 1_000;
    public const int MaximumHostFailureSafeMessageBytes = 2 * 1024;
    public const int MaximumTextSettingCharacters = 4_096;
    public const int MaximumMultilineSettingCharacters = 16_384;
    public const int MaximumSecretSettingCharacters = 4_096;
    public const int MaximumSettingChoices = 64;
    public const long MinimumIntegerSettingValue = -1_000_000_000_000;
    public const long MaximumIntegerSettingValue = 1_000_000_000_000;
    public const decimal MinimumNumberSettingValue = -1_000_000_000_000m;
    public const decimal MaximumNumberSettingValue = 1_000_000_000_000m;
    public const int MaximumNumberDecimalPlaces = 6;
    public const long MaximumDurationSettingSeconds = 31_536_000;
    public const int MaximumOrdinarySettingsJsonBytes = 64 * 1024;
    public const int MaximumReadinessReasonCharacters = 256;
    public const int MaximumSqlCharacters = 32 * 1024;
    public const int MaximumSqlParameters = 64;
    public const int MaximumSqlRows = 256;
    public const int MaximumSqlColumns = 64;
    public const int MaximumHttpUrlCharacters = 2_048;
    public const int MaximumHttpHeaders = 32;
    public const int MaximumHttpHeaderBytes = 16 * 1024;
    public const int MaximumHttpRequestBodyBytes = 256 * 1024;
    public const int MaximumHttpResponseBodyBytes = 48 * 1024;
    public const int MaximumHttpRedirects = 3;
    public const int MaximumHttpDurationMilliseconds = 10_000;
    public const int MaximumConcurrentHttpRequestsPerPlugin = 4;
    public const int MaximumWebRequestBodyBytes = 48 * 1024;
    public const int MaximumWebRequestHeaderBytes = 16 * 1024;
    public const int MaximumPageSections = 24;
    public const int MaximumPageFields = 32;
    public const int MaximumPageTableColumns = 12;
    public const int MaximumPageTableRows = 100;
    public const int MaximumPageListItems = 100;
    public const int MaximumPageMessageBytes = 48 * 1024;
    public const int MaximumPageSessions = 512;
    public const int MaximumPageMessagesPerSession = 128;
}
