<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\BlokeBot.Plugins.Contracts.Testing\BlokeBot.Plugins.Contracts.Testing.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Shouldly" />
    <PackageReference Include="TUnit" />
  </ItemGroup>
</Project>
