<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\src\BlokeBot\BlokeBot.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="TUnit" />
  </ItemGroup>

  <ItemGroup>
    <Content
      Include="..\..\src\BlokeBot\appsettings.json"
      Link="appsettings.json"
      CopyToOutputDirectory="PreserveNewest"
    />
  </ItemGroup>
</Project>
