<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\Alsi.TwitchBot\Alsi.TwitchBot.csproj" />
    <ProjectReference Include="..\BlokeBot.Eventing\BlokeBot.Eventing.csproj" />
    <ProjectReference Include="..\BlokeBot.Persistence\BlokeBot.Persistence.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <Target
    Name="RestoreNodePackages"
    Inputs="$(MSBuildProjectDirectory)/package-lock.json"
    Outputs="$(MSBuildProjectDirectory)/node_modules/.package-lock.json"
  >
    <Exec Command="npm ci" WorkingDirectory="$(MSBuildProjectDirectory)" />
  </Target>

  <Target
    Name="BuildTailwindCss"
    BeforeTargets="ComputeStaticWebAssets"
    DependsOnTargets="RestoreNodePackages"
  >
    <Exec Command="npm run css:build" WorkingDirectory="$(MSBuildProjectDirectory)" />
  </Target>
</Project>
