using System.Text;

namespace BlokeBot.Plugins.Contracts.Testing;

internal static class PluginLuaLanguageServerStubEmitter
{
    internal static string Emit(PluginAuthoringContract contract)
    {
        var output = new StringBuilder();
        _ = output.AppendLine("---@meta");
        _ = output.AppendLine();
        _ = output
            .Append("-- Generated from BlokeBot host API v")
            .Append(contract.Runtime.HostApiVersion.Value)
            .AppendLine(" for Lua 5.4.");
        _ = output.AppendLine(
            "-- Regenerate with blokebot-plugin generate; do not edit this file."
        );
        _ = output.AppendLine();
        AppendCoreTypes(contract, output);
        AppendSchemas(contract.StructuredValueSchemas, output);
        AppendUnions(contract.StructuredValueUnions, output);
        AppendHostModules(contract, output);
        return output.ToString();
    }

    private static void AppendCoreTypes(PluginAuthoringContract contract, StringBuilder output)
    {
        _ = output.AppendLine(
            "---@alias BlokeBotValue nil|boolean|number|string|BlokeBotValue[]|table<string, BlokeBotValue>"
        );
        _ = output.AppendLine(
            "---@alias BlokeBotDiagnosticLevel \"trace\"|\"information\"|\"warning\"|\"error\""
        );
        _ = output.AppendLine("---@alias BlokeBotOverlayTargetId string");
        _ = output.AppendLine("---@alias BlokeBotOverlayCueId string");
        _ = output.AppendLine("---@alias BlokeBotPointAmount string");
        _ = output.AppendLine("---@alias BlokeBotPointBalance string");
        _ = output.AppendLine("---@alias BlokeBotScheduleId string");
        _ = output.AppendLine("---@alias BlokeBotScheduleInput table<string, BlokeBotValue>");
        _ = output.AppendLine("---@alias BlokeBotSqlParameter nil|boolean|number|string");
        _ = output.AppendLine(
            "---@alias BlokeBotSqlParameters table<string, BlokeBotSqlParameter>"
        );
        _ = output.AppendLine("---@alias BlokeBotSqlRow table<string, BlokeBotSqlParameter>");
        _ = output.AppendLine("---@alias BlokeBotProtectedValue string");
        _ = output.AppendLine();
        AppendSchemas(contract.InvocationInputSchemas, output);
        _ = output.AppendLine();
        _ = output.AppendLine(
            "---@class BlokeBotInstallationSettings: table<string, BlokeBotValue>"
        );
        _ = output.AppendLine("---@class BlokeBotFeatureSettings: table<string, BlokeBotValue>");
        _ = output.AppendLine();
        _ = output.AppendLine(
            "---@alias BlokeBotHostFailureCode \"invalidArguments\"|\"contextNotPermitted\"|\"notFound\"|\"conflict\"|\"unavailable\"|\"providerRejected\""
        );
        _ = output.AppendLine(
            "---@alias BlokeBotCancellationReason \"callerRequested\"|\"pluginDisabled\"|\"pluginUpdating\"|\"workerStopping\"|\"deadlineExceeded\""
        );
        _ = output.AppendLine("---@class BlokeBotHostFailure");
        _ = output.AppendLine("---@field kind \"failed\"");
        _ = output.AppendLine("---@field code BlokeBotHostFailureCode");
        _ = output.AppendLine("---@field safeMessage string");
        _ = output.AppendLine("---@class BlokeBotHostCancellation");
        _ = output.AppendLine("---@field kind \"cancelled\"");
        _ = output.AppendLine("---@field reason BlokeBotCancellationReason");
        _ = output.AppendLine(
            "---@alias BlokeBotHostTerminalOutcome BlokeBotHostFailure|BlokeBotHostCancellation"
        );
        _ = output.AppendLine();
    }

    private static void AppendSchemas(
        IEnumerable<PluginLuaSchemaDescriptor> schemas,
        StringBuilder output
    )
    {
        foreach (var schema in schemas)
        {
            _ = output.Append("---").AppendLine(schema.Description);
            _ = output.Append("---@class ").Append(schema.LuaTypeName);
            if (schema.BaseSchema is not null)
            {
                _ = output.Append(": ").Append(schema.BaseSchema.LuaTypeName);
            }
            _ = output.AppendLine();
            foreach (var field in schema.Fields)
            {
                _ = output
                    .Append("---@field [\"")
                    .Append(field.Name)
                    .Append("\"]")
                    .Append(field.Required ? string.Empty : "?")
                    .Append(' ')
                    .Append(field.Shape.LuaTypeName)
                    .Append(" # ")
                    .AppendLine(field.Description);
            }
            _ = output.AppendLine();
        }
    }

    private static void AppendUnions(
        IEnumerable<PluginLuaUnionDescriptor> unions,
        StringBuilder output
    )
    {
        foreach (var union in unions)
        {
            _ = output.Append("---").AppendLine(union.Description);
            _ = output
                .Append("---@alias ")
                .Append(union.LuaTypeName)
                .Append(' ')
                .AppendJoin(
                    '|',
                    union.Alternatives.Select(static alternative => alternative.LuaTypeName)
                )
                .AppendLine();
            _ = output.AppendLine();
        }
    }

    private static void AppendHostModules(PluginAuthoringContract contract, StringBuilder output)
    {
        foreach (var module in contract.HostModules)
        {
            var typeName = $"BlokeBot{PascalCase(module.Id.Value)}Module";
            _ = output.Append("---@class ").AppendLine(typeName);
            _ = output.Append("local ").Append(module.Id.Value).AppendLine(" = {}");
            _ = output.AppendLine();
            foreach (var operation in module.Operations)
            {
                _ = output.Append("---").AppendLine(operation.Description);
                foreach (var parameter in operation.Parameters)
                {
                    _ = output
                        .Append("---@param ")
                        .Append(parameter.Name)
                        .Append(' ')
                        .Append(LuaType(parameter.Shape))
                        .Append(" # ")
                        .AppendLine(parameter.Description);
                }
                _ = output
                    .Append("---@return ")
                    .Append(LuaType(operation.ResultShape))
                    .Append(" # ")
                    .AppendLine(operation.ResultDescription);
                _ = output
                    .Append("function ")
                    .Append(module.Id.Value)
                    .Append('.')
                    .Append(operation.LuaFunctionName)
                    .Append('(')
                    .AppendJoin(", ", operation.Parameters.Select(parameter => parameter.Name))
                    .AppendLine(") end");
                _ = output.AppendLine();
            }
        }
        _ = output.AppendLine("---@class BlokeBot");
        _ = output.AppendLine("---@field api_version 1");
        foreach (var module in contract.HostModules)
        {
            _ = output
                .Append("---@field ")
                .Append(module.Id.Value)
                .Append(" BlokeBot")
                .Append(PascalCase(module.Id.Value))
                .AppendLine("Module");
        }
        _ = output.AppendLine("local blokebot = {");
        foreach (var module in contract.HostModules)
        {
            _ = output
                .Append("  ")
                .Append(module.Id.Value)
                .Append(" = ")
                .Append(module.Id.Value)
                .AppendLine(",");
        }
        _ = output.AppendLine("}");
        _ = output.AppendLine("return blokebot");
    }

    internal static string LuaType(PluginLuaValueShape shape) =>
        shape switch
        {
            PluginLuaValueShape.Nil => "nil",
            PluginLuaValueShape.Boolean => "boolean",
            PluginLuaValueShape.Number => "number",
            PluginLuaValueShape.String => "string",
            PluginLuaValueShape.ValueArray => "BlokeBotValue[]",
            PluginLuaValueShape.ValueMap => "table<string, BlokeBotValue>",
            PluginLuaValueShape.Context => "BlokeBotContext",
            PluginLuaValueShape.InstallationSettings => "BlokeBotInstallationSettings",
            PluginLuaValueShape.FeatureSettings => "BlokeBotFeatureSettings",
            PluginLuaValueShape.DiagnosticLevel => "BlokeBotDiagnosticLevel",
            PluginLuaValueShape.OverlayTargetId => "BlokeBotOverlayTargetId",
            PluginLuaValueShape.OverlayCueId => "BlokeBotOverlayCueId",
            PluginLuaValueShape.PointAmount => "BlokeBotPointAmount",
            PluginLuaValueShape.PointBalance => "BlokeBotPointBalance",
            PluginLuaValueShape.ScheduleInput => "BlokeBotScheduleInput",
            PluginLuaValueShape.ScheduleIntervalSeconds => "integer",
            PluginLuaValueShape.ScheduleId => "BlokeBotScheduleId",
            PluginLuaValueShape.SqlParameters => "BlokeBotSqlParameters",
            PluginLuaValueShape.SqlRows => "BlokeBotSqlRow[]",
            PluginLuaValueShape.HttpRequest => "BlokeBotHttpRequest",
            PluginLuaValueShape.HttpOutcome => "BlokeBotHttpOutcome",
        };

    internal static string PascalCase(string value) =>
        string.Concat(
            value
                .Split(['.', '-', '_'], StringSplitOptions.RemoveEmptyEntries)
                .Select(part => char.ToUpperInvariant(part[0]) + part[1..])
        );
}
