using System.Text;

namespace BlokeBot.Plugins.Contracts.Testing;

internal static class PluginLuaLanguageServerStubEmitter
{
    internal static string Emit(PluginAuthoringContract contract)
    {
        var output = new StringBuilder();
        _ = output.AppendLine("---@meta");
        _ = output.AppendLine();
        _ = output
            .Append("-- Generated from BlokeBot host API v")
            .Append(contract.Runtime.HostApiVersion.Value)
            .AppendLine(" for Lua 5.4.");
        _ = output.AppendLine(
            "-- Regenerate with blokebot-plugin generate; do not edit this file."
        );
        _ = output.AppendLine();
        AppendCoreTypes(output);
        AppendContextTypes(output);
        AppendHttpTypes(output);
        AppendHostModules(contract, output);
        return output.ToString();
    }

    private static void AppendCoreTypes(StringBuilder output)
    {
        _ = output.AppendLine(
            "---@alias BlokeBotValue nil|boolean|number|string|BlokeBotValue[]|table<string, BlokeBotValue>"
        );
        _ = output.AppendLine(
            "---@alias BlokeBotDiagnosticLevel \"trace\"|\"information\"|\"warning\"|\"error\""
        );
        _ = output.AppendLine("---@alias BlokeBotOverlayTargetId string");
        _ = output.AppendLine("---@alias BlokeBotOverlayCueId string");
        _ = output.AppendLine("---@alias BlokeBotPointAmount string");
        _ = output.AppendLine("---@alias BlokeBotPointBalance string");
        _ = output.AppendLine("---@alias BlokeBotScheduleId string");
        _ = output.AppendLine("---@alias BlokeBotScheduleInput table<string, BlokeBotValue>");
        _ = output.AppendLine("---@alias BlokeBotSqlParameter nil|boolean|number|string");
        _ = output.AppendLine(
            "---@alias BlokeBotSqlParameters table<string, BlokeBotSqlParameter>"
        );
        _ = output.AppendLine("---@alias BlokeBotSqlRow table<string, BlokeBotSqlParameter>");
        _ = output.AppendLine("---@alias BlokeBotProtectedValue string");
        _ = output.AppendLine();
        _ = output.AppendLine("---@class BlokeBotCommandInput");
        _ = output.AppendLine("---@field route string");
        _ = output.AppendLine("---@field arguments string[]");
        _ = output.AppendLine("---@class BlokeBotWebInput: table<string, BlokeBotValue>");
        _ = output.AppendLine("---@class BlokeBotPageInput: table<string, BlokeBotValue>");
        _ = output.AppendLine();
        _ = output.AppendLine(
            "---@class BlokeBotInstallationSettings: table<string, BlokeBotValue>"
        );
        _ = output.AppendLine("---@class BlokeBotFeatureSettings: table<string, BlokeBotValue>");
        _ = output.AppendLine();
        _ = output.AppendLine(
            "---@alias BlokeBotHostFailureCode \"invalidArguments\"|\"contextNotPermitted\"|\"notFound\"|\"conflict\"|\"unavailable\"|\"providerRejected\""
        );
        _ = output.AppendLine(
            "---@alias BlokeBotCancellationReason \"callerRequested\"|\"pluginDisabled\"|\"pluginUpdating\"|\"workerStopping\"|\"deadlineExceeded\""
        );
        _ = output.AppendLine("---@class BlokeBotHostFailure");
        _ = output.AppendLine("---@field kind \"failed\"");
        _ = output.AppendLine("---@field code BlokeBotHostFailureCode");
        _ = output.AppendLine("---@field safeMessage string");
        _ = output.AppendLine("---@class BlokeBotHostCancellation");
        _ = output.AppendLine("---@field kind \"cancelled\"");
        _ = output.AppendLine("---@field reason BlokeBotCancellationReason");
        _ = output.AppendLine(
            "---@alias BlokeBotHostTerminalOutcome BlokeBotHostFailure|BlokeBotHostCancellation"
        );
        _ = output.AppendLine();
    }

    private static void AppendContextTypes(StringBuilder output)
    {
        _ = output.AppendLine("---@class BlokeBotActorContext");
        _ = output.AppendLine("---@field login string");
        _ = output.AppendLine("---@field displayName string");
        _ = output.AppendLine("---@field twitchUserId? string");
        _ = output.AppendLine("---@field isBroadcaster boolean");
        _ = output.AppendLine("---@field isModerator boolean");
        _ = output.AppendLine("---@field isSubscriber boolean");
        _ = output.AppendLine("---@class BlokeBotStreamContext");
        _ = output.AppendLine("---@field streamId? string");
        _ = output.AppendLine("---@field isLive boolean");
        _ = output.AppendLine("---@class BlokeBotCommandContext");
        _ = output.AppendLine("---@field route string");
        _ = output.AppendLine("---@field arguments string[]");
        _ = output.AppendLine("---@class BlokeBotEventContext");
        _ = output.AppendLine("---@field handlerId string");
        _ = output.AppendLine("---@field source string");
        _ = output.AppendLine("---@field eventId string");
        _ = output.AppendLine("---@field occurredAt string");
        _ = output.AppendLine("---@class BlokeBotScheduleContext");
        _ = output.AppendLine("---@field handlerId string");
        _ = output.AppendLine("---@field scheduleId string");
        _ = output.AppendLine("---@field dueAt string");
        _ = output.AppendLine("---@class BlokeBotWebContext");
        _ = output.AppendLine("---@field kind \"webhook\"|\"action\"");
        _ = output.AppendLine("---@field routeId string");
        _ = output.AppendLine("---@field method string");
        _ = output.AppendLine("---@class BlokeBotAutomationContext");
        _ = output.AppendLine("---@field definitionId string");
        _ = output.AppendLine("---@field invocationId string");
        _ = output.AppendLine("---@class BlokeBotMigrationContext");
        _ = output.AppendLine("---@field migrationId string");
        _ = output.AppendLine("---@field fromVersion string");
        _ = output.AppendLine("---@field toVersion string");
        _ = output.AppendLine("---@class BlokeBotPageContext");
        _ = output.AppendLine("---@field pageId string");
        _ = output.AppendLine("---@field sessionId string");
        _ = output.AppendLine();
        _ = output.AppendLine("---@class BlokeBotContextBase");
        _ = output.AppendLine("---@field pluginId string");
        _ = output.AppendLine("---@field pluginVersion string");
        _ = output.AppendLine("---@field pluginTag string");
        _ = output.AppendLine("---@class BlokeBotInstallationContext: BlokeBotContextBase");
        _ = output.AppendLine("---@field kind \"installation\"");
        _ = output.AppendLine("---@class BlokeBotChannelContext: BlokeBotContextBase");
        _ = output.AppendLine("---@field kind \"channel\"");
        _ = output.AppendLine("---@field hostId integer");
        _ = output.AppendLine("---@field featureId string");
        _ = output.AppendLine("---@field actor? BlokeBotActorContext");
        _ = output.AppendLine("---@field stream? BlokeBotStreamContext");
        _ = output.AppendLine("---@field command? BlokeBotCommandContext");
        _ = output.AppendLine("---@field event? BlokeBotEventContext");
        _ = output.AppendLine("---@field schedule? BlokeBotScheduleContext");
        _ = output.AppendLine("---@field web? BlokeBotWebContext");
        _ = output.AppendLine("---@class BlokeBotAutomationInvocationContext: BlokeBotContextBase");
        _ = output.AppendLine("---@field kind \"automation\"");
        _ = output.AppendLine("---@field hostId integer");
        _ = output.AppendLine("---@field featureId string");
        _ = output.AppendLine("---@field automation BlokeBotAutomationContext");
        _ = output.AppendLine("---@class BlokeBotMigrationInvocationContext: BlokeBotContextBase");
        _ = output.AppendLine("---@field kind \"migration\"");
        _ = output.AppendLine("---@field migration BlokeBotMigrationContext");
        _ = output.AppendLine("---@class BlokeBotPageInvocationContext: BlokeBotContextBase");
        _ = output.AppendLine("---@field kind \"page\"");
        _ = output.AppendLine("---@field hostId integer");
        _ = output.AppendLine("---@field featureId string");
        _ = output.AppendLine("---@field page BlokeBotPageContext");
        _ = output.AppendLine(
            "---@alias BlokeBotContext BlokeBotInstallationContext|BlokeBotChannelContext|BlokeBotAutomationInvocationContext|BlokeBotMigrationInvocationContext|BlokeBotPageInvocationContext"
        );
        _ = output.AppendLine();
    }

    private static void AppendHttpTypes(StringBuilder output)
    {
        _ = output.AppendLine(
            "---@alias BlokeBotHttpMethod \"GET\"|\"POST\"|\"PUT\"|\"PATCH\"|\"DELETE\"|\"HEAD\""
        );
        _ = output.AppendLine("---@class BlokeBotHttpRequest");
        _ = output.AppendLine("---@field method BlokeBotHttpMethod");
        _ = output.AppendLine("---@field url string");
        _ = output.AppendLine("---@field headers? table<string, string>");
        _ = output.AppendLine("---@field body? string");
        _ = output.AppendLine("---@class BlokeBotHttpResponse");
        _ = output.AppendLine("---@field kind \"response\"");
        _ = output.AppendLine("---@field status integer");
        _ = output.AppendLine("---@field headers table<string, string>");
        _ = output.AppendLine("---@field bodyBase64 string");
        _ = output.AppendLine("---@class BlokeBotHttpRejected");
        _ = output.AppendLine("---@field kind \"rejected\"");
        _ = output.AppendLine("---@field code string");
        _ = output.AppendLine("---@class BlokeBotHttpFailed");
        _ = output.AppendLine("---@field kind \"failed\"");
        _ = output.AppendLine("---@field code string");
        _ = output.AppendLine(
            "---@alias BlokeBotHttpOutcome BlokeBotHttpResponse|BlokeBotHttpRejected|BlokeBotHttpFailed"
        );
        _ = output.AppendLine();
    }

    private static void AppendHostModules(PluginAuthoringContract contract, StringBuilder output)
    {
        foreach (var module in contract.HostModules)
        {
            var typeName = $"BlokeBot{PascalCase(module.Id.Value)}Module";
            _ = output.Append("---@class ").AppendLine(typeName);
            _ = output.Append("local ").Append(module.Id.Value).AppendLine(" = {}");
            _ = output.AppendLine();
            foreach (var operation in module.Operations)
            {
                _ = output.Append("---").AppendLine(operation.Description);
                foreach (var parameter in operation.Parameters)
                {
                    _ = output
                        .Append("---@param ")
                        .Append(parameter.Name)
                        .Append(' ')
                        .Append(LuaType(parameter.Shape))
                        .Append(" # ")
                        .AppendLine(parameter.Description);
                }
                _ = output
                    .Append("---@return ")
                    .Append(LuaType(operation.ResultShape))
                    .Append(" # ")
                    .AppendLine(operation.ResultDescription);
                _ = output
                    .Append("function ")
                    .Append(module.Id.Value)
                    .Append('.')
                    .Append(operation.LuaFunctionName)
                    .Append('(')
                    .AppendJoin(", ", operation.Parameters.Select(parameter => parameter.Name))
                    .AppendLine(") end");
                _ = output.AppendLine();
            }
        }
        _ = output.AppendLine("---@class BlokeBot");
        _ = output.AppendLine("---@field api_version 1");
        foreach (var module in contract.HostModules)
        {
            _ = output
                .Append("---@field ")
                .Append(module.Id.Value)
                .Append(" BlokeBot")
                .Append(PascalCase(module.Id.Value))
                .AppendLine("Module");
        }
        _ = output.AppendLine("local blokebot = {");
        foreach (var module in contract.HostModules)
        {
            _ = output
                .Append("  ")
                .Append(module.Id.Value)
                .Append(" = ")
                .Append(module.Id.Value)
                .AppendLine(",");
        }
        _ = output.AppendLine("}");
        _ = output.AppendLine("return blokebot");
    }

    internal static string LuaType(PluginLuaValueShape shape) =>
        shape switch
        {
            PluginLuaValueShape.Nil => "nil",
            PluginLuaValueShape.Boolean => "boolean",
            PluginLuaValueShape.Number => "number",
            PluginLuaValueShape.String => "string",
            PluginLuaValueShape.ValueArray => "BlokeBotValue[]",
            PluginLuaValueShape.ValueMap => "table<string, BlokeBotValue>",
            PluginLuaValueShape.Context => "BlokeBotContext",
            PluginLuaValueShape.InstallationSettings => "BlokeBotInstallationSettings",
            PluginLuaValueShape.FeatureSettings => "BlokeBotFeatureSettings",
            PluginLuaValueShape.DiagnosticLevel => "BlokeBotDiagnosticLevel",
            PluginLuaValueShape.OverlayTargetId => "BlokeBotOverlayTargetId",
            PluginLuaValueShape.OverlayCueId => "BlokeBotOverlayCueId",
            PluginLuaValueShape.PointAmount => "BlokeBotPointAmount",
            PluginLuaValueShape.PointBalance => "BlokeBotPointBalance",
            PluginLuaValueShape.ScheduleInput => "BlokeBotScheduleInput",
            PluginLuaValueShape.ScheduleIntervalSeconds => "integer",
            PluginLuaValueShape.ScheduleId => "BlokeBotScheduleId",
            PluginLuaValueShape.SqlParameters => "BlokeBotSqlParameters",
            PluginLuaValueShape.SqlRows => "BlokeBotSqlRow[]",
            PluginLuaValueShape.HttpRequest => "BlokeBotHttpRequest",
            PluginLuaValueShape.HttpOutcome => "BlokeBotHttpOutcome",
        };

    internal static string PascalCase(string value) =>
        string.Concat(
            value
                .Split(['.', '-', '_'], StringSplitOptions.RemoveEmptyEntries)
                .Select(part => char.ToUpperInvariant(part[0]) + part[1..])
        );
}
