<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\BlokeBot.Plugins.Contracts\BlokeBot.Plugins.Contracts.csproj" />
    <ProjectReference Include="..\BlokeBot.Plugins.Runtime\BlokeBot.Plugins.Runtime.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" />
  </ItemGroup>
</Project>
