<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\src\BlokeBot.Site\BlokeBot.Site.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="TUnit" />
  </ItemGroup>
</Project>
