---@meta

-- Generated from BlokeBot host API v1 for Lua 5.4.
-- Regenerate with blokebot-plugin generate; do not edit this file.

---@alias BlokeBotValue nil|boolean|number|string|BlokeBotValue[]|table<string, BlokeBotValue>
---@alias BlokeBotDiagnosticLevel "trace"|"information"|"warning"|"error"
---@alias BlokeBotOverlayTargetId string
---@alias BlokeBotOverlayCueId string
---@alias BlokeBotPointAmount string
---@alias BlokeBotPointBalance string
---@alias BlokeBotScheduleId string
---@alias BlokeBotScheduleInput table<string, BlokeBotValue>
---@alias BlokeBotSqlParameter nil|boolean|number|string
---@alias BlokeBotSqlParameters table<string, BlokeBotSqlParameter>
---@alias BlokeBotSqlRow table<string, BlokeBotSqlParameter>
---@alias BlokeBotProtectedValue string

---Input delivered to a declared command handler.
---@class BlokeBotCommandInput
---@field ["route"] string # The normalized command route.
---@field ["arguments"] string[] # The ordered command arguments.

---Input delivered to declared webhook, HTTP action, and webhook authentication handlers.
---@class BlokeBotWebInput
---@field ["method"] string # The uppercase HTTP method.
---@field ["headers"] table<string, string> # The request headers with lowercase names.
---@field ["bodyBase64"] string # The request body encoded as base64.

---Input delivered to a generated page renderer.
---@class BlokeBotPageInput
---@field ["version"] integer # The generated page input version.
---@field ["hostId"] integer # The selected BlokeBot host ID.
---@field ["sessionId"] string # The generated page session ID.

---Input delivered for a declared BlokeBot event.
---@class BlokeBotEventInput
---@field ["event_id"] string # The stable event correlation ID.
---@field ["source"] string # The canonical event source name.

---Input delivered for a declared typed Twitch event.
---@class BlokeBotTwitchEventInput
---@field ["event_id"] string # The stable event correlation ID.
---@field ["source"] string # The canonical event source name.
---@field ["occurred_at"] string # The UTC event timestamp in round-trip format.

---Subscription identity included with a raw Twitch event.
---@class BlokeBotTwitchRawSubscription
---@field ["type"] string # The EventSub subscription type.
---@field ["version"] string # The EventSub subscription version.

---Input delivered for a declared raw Twitch EventSub event.
---@class BlokeBotTwitchRawEventInput
---@field ["subscription"] BlokeBotTwitchRawSubscription # The raw EventSub subscription identity.
---@field ["event"] table<string, BlokeBotValue> # The raw EventSub event payload.

---Input delivered to a declared migration handler.
---@class BlokeBotMigrationInput
---@field ["migrationId"] string # The declared migration ID.
---@field ["fromVersion"] string # The source semantic version.
---@field ["toVersion"] string # The target semantic version.


---@class BlokeBotInstallationSettings: table<string, BlokeBotValue>
---@class BlokeBotFeatureSettings: table<string, BlokeBotValue>

---@alias BlokeBotHostFailureCode "invalidArguments"|"contextNotPermitted"|"notFound"|"conflict"|"unavailable"|"providerRejected"
---@alias BlokeBotCancellationReason "callerRequested"|"pluginDisabled"|"pluginUpdating"|"workerStopping"|"deadlineExceeded"
---@class BlokeBotHostFailure
---@field kind "failed"
---@field code BlokeBotHostFailureCode
---@field safeMessage string
---@class BlokeBotHostCancellation
---@field kind "cancelled"
---@field reason BlokeBotCancellationReason
---@alias BlokeBotHostTerminalOutcome BlokeBotHostFailure|BlokeBotHostCancellation

---The admitted channel actor.
---@class BlokeBotActorContext
---@field ["login"] string # The actor's normalized login.
---@field ["displayName"] string # The actor's display name.
---@field ["twitchUserId"]? string # The actor's Twitch user ID.
---@field ["isBroadcaster"] boolean # Whether the actor is the broadcaster.
---@field ["isModerator"] boolean # Whether the actor is a moderator.
---@field ["isSubscriber"] boolean # Whether the actor is a subscriber.

---The admitted stream state.
---@class BlokeBotStreamContext
---@field ["streamId"]? string # The current Twitch stream ID.
---@field ["isLive"] boolean # Whether the channel is live.

---The admitted command invocation.
---@class BlokeBotCommandContext
---@field ["route"] string # The normalized command route.
---@field ["arguments"] string[] # The ordered command arguments.

---The admitted event invocation.
---@class BlokeBotEventContext
---@field ["handlerId"] string # The declared event handler ID.
---@field ["source"] string # The canonical event source.
---@field ["eventId"] string # The stable event correlation ID.
---@field ["occurredAt"] string # The UTC event timestamp.

---The admitted schedule invocation.
---@class BlokeBotScheduleContext
---@field ["handlerId"] string # The declared schedule handler ID.
---@field ["scheduleId"] string # The schedule invocation ID.
---@field ["dueAt"] string # The UTC scheduled time.

---The admitted HTTP invocation.
---@class BlokeBotWebContext
---@field ["kind"] "webhook"|"action" # The HTTP admission surface.
---@field ["routeId"] string # The declared webhook or HTTP action ID.
---@field ["method"] string # The uppercase HTTP method.

---The admitted automation invocation.
---@class BlokeBotAutomationContext
---@field ["definitionId"] string # The automation definition ID.
---@field ["invocationId"] string # The automation invocation ID.

---The admitted migration identity.
---@class BlokeBotMigrationContext
---@field ["migrationId"] string # The declared migration ID.
---@field ["fromVersion"] string # The source semantic version.
---@field ["toVersion"] string # The target semantic version.

---The admitted page identity.
---@class BlokeBotPageContext
---@field ["pageId"] string # The declared page ID.
---@field ["sessionId"] string # The generated page session ID.

---Fields common to every admitted invocation context.
---@class BlokeBotContextBase
---@field ["pluginId"] string # The invoking plugin ID.
---@field ["pluginVersion"] string # The invoking plugin version.
---@field ["pluginTag"] string # The invoking plugin release tag.

---An installation lifecycle invocation.
---@class BlokeBotInstallationContext: BlokeBotContextBase
---@field ["kind"] "installation" # The context kind.

---A channel-scoped invocation.
---@class BlokeBotChannelContext: BlokeBotContextBase
---@field ["kind"] "channel" # The context kind.
---@field ["hostId"] integer # The selected BlokeBot host ID.
---@field ["featureId"] string # The admitted plugin feature ID.
---@field ["actor"]? BlokeBotActorContext # The admitted actor.
---@field ["stream"]? BlokeBotStreamContext # The current stream.
---@field ["command"]? BlokeBotCommandContext # The command invocation.
---@field ["event"]? BlokeBotEventContext # The event invocation.
---@field ["schedule"]? BlokeBotScheduleContext # The schedule invocation.
---@field ["web"]? BlokeBotWebContext # The HTTP invocation.

---An automation invocation.
---@class BlokeBotAutomationInvocationContext: BlokeBotContextBase
---@field ["kind"] "automation" # The context kind.
---@field ["hostId"] integer # The selected BlokeBot host ID.
---@field ["featureId"] string # The admitted plugin feature ID.
---@field ["automation"] BlokeBotAutomationContext # The automation invocation.

---A migration invocation.
---@class BlokeBotMigrationInvocationContext: BlokeBotContextBase
---@field ["kind"] "migration" # The context kind.
---@field ["migration"] BlokeBotMigrationContext # The migration identity.

---A plugin page invocation.
---@class BlokeBotPageInvocationContext: BlokeBotContextBase
---@field ["kind"] "page" # The context kind.
---@field ["hostId"] integer # The selected BlokeBot host ID.
---@field ["featureId"] string # The admitted plugin feature ID.
---@field ["page"] BlokeBotPageContext # The page identity.

---An outbound HTTP request.
---@class BlokeBotHttpRequest
---@field ["method"] "GET"|"POST"|"PUT"|"PATCH"|"DELETE"|"HEAD" # The HTTP method.
---@field ["url"] string # The absolute HTTP or HTTPS URL.
---@field ["headers"]? table<string, string> # Optional request headers.
---@field ["body"]? string # Optional UTF-8 request body.

---A completed HTTP response.
---@class BlokeBotHttpResponse
---@field ["kind"] "response" # The HTTP outcome kind.
---@field ["status"] integer # The HTTP response status.
---@field ["headers"] table<string, string> # The response headers.
---@field ["bodyBase64"] string # The response body encoded as base64.

---An HTTP request rejected before transport.
---@class BlokeBotHttpRejected
---@field ["kind"] "rejected" # The HTTP outcome kind.
---@field ["code"] string # The stable HTTP rejection code.

---An HTTP transport failure.
---@class BlokeBotHttpFailed
---@field ["kind"] "failed" # The HTTP outcome kind.
---@field ["code"] string # The stable HTTP failure code.

---The exact admitted invocation context.
---@alias BlokeBotContext BlokeBotInstallationContext|BlokeBotChannelContext|BlokeBotAutomationInvocationContext|BlokeBotMigrationInvocationContext|BlokeBotPageInvocationContext

---The typed outbound HTTP outcome.
---@alias BlokeBotHttpOutcome BlokeBotHttpResponse|BlokeBotHttpRejected|BlokeBotHttpFailed

---@class BlokeBotContextModule
local context = {}

---Returns the admitted invocation context. Plugin and feature identities cannot be supplied by the caller.
---@return BlokeBotContext # The exact installation, channel, automation, migration, or page context.
function context.current() end

---@class BlokeBotSettingsModule
local settings = {}

---Returns configured installation settings declared by this plugin.
---@return BlokeBotInstallationSettings # The plugin-specific installation settings.
function settings.installation() end

---Returns configured settings for the admitted host feature.
---@return BlokeBotFeatureSettings # The plugin-specific feature settings.
function settings.feature() end

---@class BlokeBotDiagnosticsModule
local diagnostics = {}

---Writes a redaction-safe plugin diagnostic.
---@param level BlokeBotDiagnosticLevel # The diagnostic severity.
---@param message string # The safe diagnostic text.
---@return nil # No value.
function diagnostics.log(level, message) end

---@class BlokeBotResponsesModule
local responses = {}

---Replies in the admitted channel.
---@param message string # The response text.
---@return nil # No value.
function responses.chat(message) end

---Replies privately to the admitted actor.
---@param message string # The response text.
---@return nil # No value.
function responses.whisper(message) end

---@class BlokeBotChatModule
local chat = {}

---Sends a message to the admitted channel.
---@param message string # The chat message text.
---@return nil # No value.
function chat.send(message) end

---@class BlokeBotOverlayModule
local overlay = {}

---Admits an overlay cue for the current channel.
---@param target_id BlokeBotOverlayTargetId # The overlay target UUID.
---@param cue_id BlokeBotOverlayCueId # The overlay cue UUID.
---@return nil # No value.
function overlay.play_cue(target_id, cue_id) end

---@class BlokeBotPointsModule
local points = {}

---Adds a non-negative point amount to a viewer balance.
---@param viewer string # The viewer login.
---@param amount BlokeBotPointAmount # The invariant non-negative amount.
---@param reason string # The audit reason.
---@return BlokeBotPointBalance # The resulting invariant balance.
function points.add(viewer, amount, reason) end

---@class BlokeBotTwitchModule
local twitch = {}

---Creates a Twitch stream marker for the admitted channel.
---@param description string # The marker description.
---@return nil # No value.
function twitch.create_marker(description) end

---@class BlokeBotSchedulesModule
local schedules = {}

---Creates a one-time feature schedule.
---@param handler_id string # The declared handler ID.
---@param due_at string # The future UTC timestamp in ISO 8601 format.
---@param input BlokeBotScheduleInput # The handler input.
---@return BlokeBotScheduleId # The new schedule UUID.
function schedules.once(handler_id, due_at, input) end

---Creates a recurring feature schedule.
---@param handler_id string # The declared handler ID.
---@param due_at string # The first future UTC timestamp in ISO 8601 format.
---@param interval_seconds integer # The positive whole-second interval.
---@param input BlokeBotScheduleInput # The handler input.
---@return BlokeBotScheduleId # The new schedule UUID.
function schedules.recurring(handler_id, due_at, interval_seconds, input) end

---Cancels a schedule owned by the current feature generation.
---@param schedule_id BlokeBotScheduleId # The schedule UUID.
---@return nil # No value.
function schedules.cancel(schedule_id) end

---@class BlokeBotStorageModule
local storage = {}

---Executes one supported statement against plugin-private SQLite.
---@param sql string # The SQL statement.
---@param parameters BlokeBotSqlParameters # Named scalar parameters without the SQL prefix.
---@return number # The number of changed rows.
function storage.execute(sql, parameters) end

---Queries plugin-private SQLite.
---@param sql string # The SQL query.
---@param parameters BlokeBotSqlParameters # Named scalar parameters without the SQL prefix.
---@return BlokeBotSqlRow[] # The result rows keyed by column name.
function storage.query(sql, parameters) end

---@class BlokeBotHttpModule
local http = {}

---Sends a bounded outbound HTTP request through the host policy.
---@param request BlokeBotHttpRequest # The method, absolute URL, optional headers, and optional UTF-8 body.
---@return BlokeBotHttpOutcome # A tagged response, rejection, or transport failure.
function http.send(request) end

---@class BlokeBot
---@field api_version 1
---@field context BlokeBotContextModule
---@field settings BlokeBotSettingsModule
---@field diagnostics BlokeBotDiagnosticsModule
---@field responses BlokeBotResponsesModule
---@field chat BlokeBotChatModule
---@field overlay BlokeBotOverlayModule
---@field points BlokeBotPointsModule
---@field twitch BlokeBotTwitchModule
---@field schedules BlokeBotSchedulesModule
---@field storage BlokeBotStorageModule
---@field http BlokeBotHttpModule
local blokebot = {
  context = context,
  settings = settings,
  diagnostics = diagnostics,
  responses = responses,
  chat = chat,
  overlay = overlay,
  points = points,
  twitch = twitch,
  schedules = schedules,
  storage = storage,
  http = http,
}
return blokebot
