<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\BlokeBot.Persistence\BlokeBot.Persistence.csproj" />
    <ProjectReference Include="..\BlokeBot.Persistence.PostgreSql\BlokeBot.Persistence.PostgreSql.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Catalog\domain-tables.txt" />
  </ItemGroup>
</Project>
